# Generated by Django 5.2 on 2025-04-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product_list',
            new_name='product',
        ),
    ]
