# Generated by Django 5.2 on 2025-04-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_list_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryy',
            new_name='categories',
        ),
    ]
