# Generated by Django 5.2 on 2025-04-25 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_unit_price_orderitem_price_per_killo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Addis Ababa', 'Addis Ababa')], max_length=255)),
                ('city', models.CharField(choices=[('Addis Ababa', 'Addis Ababa')], max_length=255)),
                ('zone', models.CharField(choices=[('Arada', 'Arada')], max_length=255)),
                ('woreda', models.CharField(choices=[('01', '01')], max_length=255)),
                ('kebele', models.CharField(choices=[('01', '01')], max_length=255)),
                ('street', models.CharField(choices=[('Street Name', 'Street Name')], max_length=255)),
                ('house_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='streat',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='store.address'),
            preserve_default=False,
        ),
    ]
