# Generated by Django 5.2 on 2025-05-10 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_address_remove_customer_city_remove_customer_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa')], max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='kebele',
            field=models.CharField(choices=[('01', '01'), ('01', '01'), ('01', '01'), ('01', '01'), ('01', '01'), ('01', '01'), ('01', '01'), ('01', '01')], max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa'), ('Addis Ababa', 'Addis Ababa')], max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(choices=[('Street Name', 'Street Name'), ('Street Name', 'Street Name'), ('Street Name', 'Street Name'), ('Street Name', 'Street Name'), ('Street Name', 'Street Name'), ('Street Name', 'Street Name'), ('Street Name', 'Street Name')], max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='woreda',
            field=models.CharField(choices=[('01', '01'), ('01', '01'), ('01', '01'), ('01', '01'), ('01', '01'), ('01', '01'), ('01', '01'), ('01', '01')], max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='zone',
            field=models.CharField(choices=[('Arada', 'Arada'), ('Arada', 'Arada'), ('Arada', 'Arada'), ('Arada', 'Arada'), ('Arada', 'Arada'), ('Arada', 'Arada'), ('Arada', 'Arada'), ('Arada', 'Arada'), ('Arada', 'Arada')], max_length=255),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comments', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='address', to='store.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('download_url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='store.customer')),
            ],
        ),
    ]
